### PR TITLE
Implementing strata and hierarchy slots

### PR DESCRIPTION
**Pull request by zkamvar**
This merge addresses #16 and will largely contain new methods for strata and hierarchies as well as some minor bug fixes.

### New Features

All of the data objects have had the hierarchy and strata slots added and set to `NULL`. This was done using [this script](https://gist.github.com/zkamvar/50c4a98e67aa2a697339) and `devtools::use_data()`. Note, that the names of the extensions changed from `.Rdata` to `.rda`. 

 - Strata slot: data frame or NULL, genind and genlight
    - methods:
        - `strata()`: accessor and setter
        - `addstrata()`: appends a column
        - `namestrata()`: renames the strata
        - `splitstrata()`: allows the user to upload concatenated strata with their input file. This function splits those strata afterwards.
 - Hierarchy slot: formula or NULL, genind and genlight
    - methods:
         - `hierarchy()` sets and accesses the hierarchy. The accessor checks if the query is in the right order. The setter checks if the strata are set, and it needs to check if the formula is indeed hierarchical (currently no method to enforce this). @jgx65 or @ericarcher might have solutions.
 - `nPop()`: self explanitory. For genind, genpop, genlight
 - `popNames()`: self explanitory. For genind, genpop, genlight
 - `setpop()`: sets the pop slot to any combination of strata given by the user.

### Tests

I have implemented tests using the `testthat` package. They live in the `tests/testthat` directory. These unit tests are sanity checks to make sure that everything runs as expected. By default, I'm having these not test on CRAN (by using `skip_on_cran()` in every test), but they can be tested on our machines by running `devtools::test()` in the package directory. 

The main idea behind these tests is to write a test every time you squish a bug. This way, if the bug evolves, you know where to squash it again. 

### Package imports

- dplyr for an efficient way to combine rows of several data frames (for `repool`)
- reshape2 for splitting columns.

### Bugs squashed

- microbov still had generic names for `loc.nall`.
- `df2genind()` can now handle haploid data with uneven allele names 
- `df2genind()` can handle matrices without any sample or locus names.
- `df2genind()` will now drop > 0 non-type loci (it was tolerating one).

### CODE REVIEW

**Comment by thibautjombart** [comment]
This looks great! Thanks a lot for all the work - that's a major addition for version 2.0-0! 
Question: what is the difference between
```r
setpop(x,yyy)
```
and
```r
pop(x) <- yyy
```
For consistency, I like to have the slot replacement methods defined as
```r
accessor(x) <- newvalue
```
 Also so far we're using camelCase for methods (indNames, locNames etc) so setPop would make sense?

**Comment by thibautjombart** [comment]
I am merging anyway. Feel free to make adjustments on the master or to fork again if needed.

**Comment by zkamvar** [comment]
The inherent difference between 

```r
# Both are valid as long as yyy is a formula
setpop(x, yyy)
setpop(x) <- yyy
```

and

```r
# yyy must be a vector
pop(x) <- yyy
```

is that setpop **must** take a formula that names a column or columns in the strata slot. pop allows the users to manipulate the population with an outside vector. Basically, the pop slot and the strata slot are relatively agnostic to each other except in accessor setpop. If only one stratification is used, the accessor is roughly equivalent to:

```r
# equivalent
setpop(x) <- ~yyy
pop(x) <- strata(x, ~yyy)[[1]]
```

If more than one are used, it becomes more along the lines of:

```r
# equivalent
setpop(x) ~yyy/zzz
pop(x) <- apply(strata(x, ~yyy/zzz, combine = FALSE), 1, paste, collapse = "_")
```

I had not realized that camelCase was explicitly for methods (I always went with lower case to make things easier to type). I can change it easily. In that case, I assume that [addstrata, splitstrata, and namestrata] should become [addStrata, splitStrata, and nameStrata]?

**Comment by thibautjombart** [comment]
OK, great, thanks for the clarification.
Yes regarding the camelCase thing. It is not universally respected across
the package, but I'm trying to stick to it now.

**Comment by thibautjombart** [comment]
BTW I'm thinking the stratification might be documented in its own
tutorial.

**Comment by zkamvar** [comment]
I had the exact same thought.

**Comment by thibautjombart** [comment]
Which reminds me I need to put all tutorials at this new repos. Will post
an issue..

**Pull request merged**
