### PR TITLE
parallel support for xvalDapc

### PR DESCRIPTION
**Pull request by zkamvar**
I have implemented parallel support for xvalDapc in the branch xval_parallel. This is done via the package *boot*. Tests on my mac show half the processing time with two cores on 1000 samplings. The boot function can take parallel support by specifying which parallel package is used (*multicore* for mac, I think it's *snow* for windows, but I'm not sure) and how many cores are specified. Regarding speed, I think this might be a welcome addition for users.

### CODE REVIEW

**Comment by thibautjombart** [comment]
Sounds cool!
Speedup will be welcome indeed. I think parallel is now supposed to replace
multicore and snow, so it may be the way to go. Used it for outbreaker, but
implementation on windows is a bit cumbersome. Or we decide to have
parallelization on unix/linux.
Caitlin should have a look to check she's happy with the changes.
But again, cool stuff!
Cheers
Thibaut

**Comment by romunov** [comment]
FWIW, I have good experience with `parallel` on Windows. It's just sexed up snow (syntax-wise).

**Comment by thibautjombart** [comment]
I saw this one, will merge soon.

**Comment by zkamvar** [comment]
Before you merge it, I need to merge @caitiecollins' changes that she made after I submitted this pull request.

**Comment by thibautjombart** [comment]
Right I'll let you get on with this bit then.

**Comment by caitiecollins** [comment]
Thanks again for handling that merge, Zhian. Parallel xval is going to be
super cool (for other people with better computers than mine, lol).

Cheers,
CC.

**Comment by zkamvar** [comment]
I believe this should work now. 

The rundown of how this is modified from the original is that I split up the function `get.prop.pred` into three worker functions and a wrapper. 

- `.get.prop.pred()` will check if all the populations are N > 10 and then call the function boot from the boot package. 
    - `.boot_dapc_pred()` generates the prediction. It serves as the `statistic` parameter for `boot()`
    - `.boot_group_sampler()` is the parametric sampler to randomly sample per group. Serves as the `ran.gen` parameter for `boot()`
        - `.group_sampler()` is the backbone of `.boot_group_sampler()` This samples given the training set fraction unless the group only has one member.

**Comment by zkamvar** [comment]
You can test it with this:

```r
data(nancycats)
x <- nancycats
mat <- tab(x, freq = TRUE, NA.method = "mean")
grp <- pop(x)
# Serial
set.seed(20150327)
system.time(xval <- xvalDapc(mat, grp, n.pca.max = 300, training.set = 0.9,
                 result = "groupMean", center = TRUE, scale = FALSE,
                 n.pca = NULL, n.rep = 100, xval.plot = TRUE))
set.seed(20150327)
# 4 cores 
system.time(xval <- xvalDapc(mat, grp, n.pca.max = 300, training.set = 0.9,
                             result = "groupMean", center = TRUE, scale = FALSE,
                             n.pca = NULL, n.rep = 100, xval.plot = TRUE, 
                             parallel = "multicore", ncpus = 4))
set.seed(20150327)
# 8 cores
system.time(xval <- xvalDapc(mat, grp, n.pca.max = 300, training.set = 0.9,
                             result = "groupMean", center = TRUE, scale = FALSE,
                             n.pca = NULL, n.rep = 100, xval.plot = TRUE, 
                             parallel = "multicore", ncpus = 8))
set.seed(20150327)
# 2 cores
system.time(xval <- xvalDapc(mat, grp, n.pca.max = 300, training.set = 0.9,
                             result = "groupMean", center = TRUE, scale = FALSE,
                             n.pca = NULL, n.rep = 100, xval.plot = TRUE, 
                             parallel = "multicore", ncpus = 2))
```

**Comment by zkamvar** [comment]
Also: I **JUST** noticed [this line](https://github.com/thibautjombart/adegenet/blob/2b1cfad3797e2cb1ff246f4458e819557cdc3af6/R/xvalDapc.R#L241): 

```r
cait<-sapply(lin, function(e) ((col[lins[,e]])-1)^2)
```

**Comment by thibautjombart** [comment]
???

**Comment by thibautjombart** [comment]
???

**Comment by thibautjombart** [comment]
Pulled and merged with master as of 40e108c701a9cdd29d04
Was only minor a minor conflict to resolve.

**Comment by thibautjombart** [comment]
Thanks team!! =D

**Pull request merged**
