### PR TITLE
Speed up df2genind

### PR DESCRIPTION
**Pull request by KlausVigo**
Hi Thibaut,

how are things? We are analyzing some RADseq data in our lab and could not transform a vcf files to genind objects. `df2genind` run out of memory and R stalled. 
So I made some improvements to `df2genind`. This code seems to work as intended, but maybe you have to check with some more tricky data sets to test it more thorough. 

E.g. the following code take now .2 seconds instead of 6 seconds on my machine.
```
library(adegenet)
library(vcfR)

data(vcfR_example)
my_genind <- vcfR2genind(vcf)
```
It should also be possible to transform larger data sets, which should be useful for quite a few people. 

I also cleaned up some code, e.g. replace `paste()` with `paste0()` or using `lengths(x)` instead of `sapply(x, length)`. 

Cheers, 
Klaus

### CODE REVIEW

**Comment by thibautjombart** [comment]
Hi Klaus 
thanks a lot for this. I am swamped with work on Ebola atm so not sure when I have time to get to this, do not hesitate to poke!

**Comment by KlausVigo** [comment]
Hi @zkamvar, 
I now need to complain to you that the pull request is not yet handled ; )
Thanks for taking on the responsibility. 
Cheers, 
Klaus

**Comment by zkamvar** [comment]
> Hi @zkamvar,
> I now need to complain to you that the pull request is not yet handled ; )
> Thanks for taking on the responsibility.
> Cheers,
> Klaus

Hi Klaus,

Yes, you are correct that I am the person to bug about this. I'm re-running the PR just to make sure it passes check (I have no doubt it will) and then I'll merge it :)

**Comment by zkamvar** [comment]
Okay, it passes check and I have confirmed the speedup. Thank you for adding this!

**Pull request merged**
