### PR TITLE
Closing parenthesis in find.clusters() choose the number of clusters

### PR DESCRIPTION
**Pull request by knausb**
A user of our website found this. Thanks!

### CODE REVIEW

**Comment by romunov** [comment]
Can you merge your two commits into one?

**Comment by zkamvar** [comment]
We can squash it from here, @romunov. Thanks, @knausb!

**Comment by knausb** [comment]
Sorry about that @romunov ! It looked like such a simple PR that I could manage it on GitHub. Looks like I found a way to munge it. Thank you @zkamvar for sorting it out!

**Comment by romunov** [comment]
@knausb it's a learning process. Fixing my own git mistakes takes half of my time. :)

**Pull request merged**
