### PR TITLE
SNPbin fix

### PR DESCRIPTION
**Pull request by zkamvar**
This will fix issue #83

I have changed the subsetter for both SNPbin and genlight objects.

### CODE REVIEW

**Comment by thibautjombart** [comment]
Apparently the checks failed. Fishing around in the long log:
```r
* checking tests ... ERROR
Running the tests in â€˜tests/testthat.Râ€™ failed.
Last 13 lines of output:
  'citation()' on how to cite R or R packages in publications.
  
  Type 'demo()' for some demos, 'help()' for on-line help, or
  'help.start()' for an HTML browser interface to help.
  Type 'q()' to quit R.
  
  > library(testthat)
  > suppressPackageStartupMessages(library(adegenet))
  > test_check("adegenet")
  Loading required package: parallel
  Error in .check_ncores(cores) : 32 simultaneous processes spawned
  Calls: test_check ... initialize -> initialize -> .local -> mclapply -> .check_ncores
  Execution halted
* checking PDF version of manual ... OK
* DONE
Status: 1 ERROR, 3 NOTEs
```

Note the 32 cores used. This is really bad. We need to limit the number of cores used by default when using `mclapply`.

**Comment by zkamvar** [comment]
That is frightening. I'll set parallel = FALSE on the genlight constructor and try again. Luckily none of these tests run on CRAN

**Comment by zkamvar** [comment]
Hooray! Things are passing!

**Comment by thibautjombart** [comment]
=D

**Comment by thibautjombart** [comment]
Outstanding - thanks!

**Pull request merged**
