### PR TITLE
set n.cores=1 for Windows

### PR DESCRIPTION
**Pull request by knausb**
Hello,

I've forked and made my proposed changes. It tests and builds in Ubuntu. I've successfully built it at win-builder and tested this binary on a colleague's Windows machine and the person who originally brought this issue to my attention has tested it on their Windows machine. The diff appears to show a lot of changes (this is my first pull request). But most of them appear to be punctuation or versioning. Let me know if you need any other info.

Thanks!
Brian

### CODE REVIEW

**Comment by romunov** [comment]
The package checks out OK on my 64 bit W7.

**Comment by zkamvar** [comment]
@thibautjombart, is this okay with you for merging?

**Comment by thibautjombart** [comment]
Sorry for the delay. Merging now. Thanks for the patch!

**Comment by thibautjombart** [comment]
@knausb I've added you there:
https://github.com/thibautjombart/adegenet/wiki/Contributors

Let me know if you'd like to link to a different URL. Also adding you to the authors in DESCRIPTION.

**Comment by knausb** [comment]
Wow! I was not expecting to be added as a contributor. I suppose an argument could be made that I may have had some sort of unique background to help in this situation. But at the end of the day, I think we're talking about 3 lines of code. But your link to the plots of contributor activity does make it transparent that I'm not pulling the heavy weight on this project. And if you're happy including me as a contributor, the URL you've chosen is fine. Thanks! (And thanks for agegenet!)

**Comment by thibautjombart** [comment]
@knausb the more the merrier, and you technically contributed! Welcome to the team!

**Pull request merged**
