### PR TITLE
Exp dapc label inds

### PR DESCRIPTION
**Pull request by romunov**
Added new argument `label.inds` to `scatter.dapc`.

### CODE REVIEW

**Comment by zkamvar** [comment]
It looks good to me. I updated the documentation to make it clearer.

**Comment by romunov** [comment]
Perfect, thanks.

**Comment by thibautjombart** [comment]
Looks great, thanks for the add! 
(Sorry I won't be very reactive until the second week of December.)

**Comment by romunov** [comment]
Enjoy your vacation time, we need you fresh and alert. :)

**Pull request merged**
