### PR TITLE
adding swallowtail test data

### PR DESCRIPTION
**Pull request by jrdupuis**
For export_to_mvmapper example data

### CODE REVIEW

**Comment by thibautjombart** [comment]
Thanks!

**Comment by zkamvar** [comment]
Hi @jrdupuis,

Could you add documentation for the `swallowtails` data?

**Comment by jrdupuis** [comment]
@zkamvar There is a reference in `export_to_mvmapper.R` to the paper where that data was generated (https://doi.org/10.1111/jeb.12931), and I have clarified that point. Is there another way to document such a dataset? Sorry, my R know-how is not extensive!

**Comment by zkamvar** [comment]
This is mainly because we are getting a warning from R CMD check about it:

checking for missing documentation entries ... WARNING
Undocumented data sets:
  ‘swallowtails’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.

Here's a short writeup of how to do that:
http://r-pkgs.had.co.nz/data.html#documenting-data

**Pull request merged**
