### PR TITLE
Fix scaleGen example and use Authors@R 

### LINKED ISSUE #254: spurious argument "met =" in examples scaleGen?
Dear developpers,

There seem to be a small hick-up in the examples for scaleGen:
```
example(scaleGen, run.dontrun = TRUE)
```
gives the following error:
```
scalGn> X2 <- scaleGen(obj,met="bin")
Error in .local(x, ...) : unused argument (met = "bin")
```
and I am not sure where the "met = " is coming from.

Tested on:

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dendextend_1.9.0  viridis_0.5.1     viridisLite_0.3.0
 [4] lattice_0.20-38   ggplot2_3.1.0     pegas_0.11       
 [7] ape_5.2           poppr_2.8.1       adegenet_2.1.1   
[10] ade4_1.7-13      

loaded via a namespace (and not attached):
 [1] nlme_3.1-137        webshot_0.5.1       gmodels_2.18.1     
 [4] progress_1.2.0      httr_1.4.0          prabclus_2.2-7     
 [7] tools_3.5.2         polysat_1.7-3       R6_2.3.0           
[10] vegan_2.5-4         spData_0.3.0        lazyeval_0.2.1     
[13] mgcv_1.8-27         colorspace_1.4-0    trimcluster_0.1-2.1
[16] nnet_7.3-12         permute_0.9-4       withr_2.1.2        
[19] sp_1.3-1            tidyselect_0.2.5    gridExtra_2.3      
[22] prettyunits_1.0.2   phangorn_2.4.0      compiler_3.5.2     
[25] rvest_0.3.2         expm_0.999-3        xml2_1.2.0         
[28] labeling_0.3        diptest_0.75-7      scales_1.0.0       
[31] DEoptimR_1.0-8      robustbase_0.93-3   mvtnorm_1.0-8      
[34] readr_1.3.1         quadprog_1.5-5      stringr_1.3.1      
[37] digest_0.6.18       rmarkdown_1.11      pkgconfig_2.0.2    
[40] htmltools_0.3.6     highr_0.7           rlang_0.3.1        
[43] rstudioapi_0.9.0    shiny_1.2.0         bindr_0.1.1        
[46] mclust_5.4.2        gtools_3.8.1        spdep_0.8-1        
[49] dplyr_0.7.8         magrittr_1.5        modeltools_0.2-22  
[52] kableExtra_1.0.1    Matrix_1.2-15       Rcpp_1.0.0         
[55] munsell_0.5.0       whisker_0.3-2       stringi_1.2.4      
[58] yaml_2.2.0          MASS_7.3-51.1       flexmix_2.3-14     
[61] plyr_1.8.4          grid_3.5.2          parallel_3.5.2     
[64] gdata_2.18.0        promises_1.0.1      crayon_1.3.4       
[67] deldir_0.1-16       splines_3.5.2       hms_0.4.2          
[70] knitr_1.21          pillar_1.3.1        igraph_1.2.2       
[73] boot_1.3-20         fpc_2.1-11.1        seqinr_3.4-5       
[76] stats4_3.5.2        reshape2_1.4.3      fastmatch_1.1-0    
[79] LearnBayes_2.15.1   glue_1.3.0          evaluate_0.12      
[82] httpuv_1.4.5.1      gtable_0.2.0        purrr_0.3.0        
[85] tidyr_0.8.2         kernlab_0.9-27      assertthat_0.2.0   
[88] xfun_0.4            mime_0.6            xtable_1.8-3       
[91] coda_0.19-2         later_0.7.5         class_7.3-15       
[94] rsconnect_0.8.13    tibble_2.0.1        bindrcpp_0.2.2     
[97] cluster_2.0.7-1    
> 
```

Best,

Alex

### LINKED ISSUE #255: typo in doc
In `?find.cluster`:

There is a typo in the following sentence
```
 First important result is that BIC seems for efficient than AIC and WSS to...
```
which should read
```
 First important result is that BIC seems MORE efficient than AIC and WSS to...
```
++

### PR DESCRIPTION
**Pull request by courtiol**
This PR solves 2 old issues:

Fixes #255, a small typo in the doc

Fixes #254, a broken example

For #254 the core idea that was there (comparing different scaling methods) cannot be applied because the function `scaleGen()` does not allow for such a thing. I tried to follow the original spirit as much as possible by comparing scaling in-PCA vs using `scaleGen()`, but it is not particularly insightful so an alternative would be to cut short the example.

### CODE REVIEW

**Comment by zkamvar** [comment]
Hi @courtiol, would you mind adding yourself to the Authors field in the DESCRIPTION file with a [ctb] tag?

**Comment by courtiol** [comment]
@zkamvar I took the opportunity to refresh a bit the DESCRIPTION file, so please double check.
I switched the declaration of authorship to the more modern Authors@R syntax.
That implied that I had to fill in the tags which were not present.
I listed all as ctb but you ("cre" + "aut") and @thibautjombart ("aut").
I added your ORCID number but did not bother with the others.
I did try for @thibautjombart  but could not make sure of which ORCID number was good as several profile exist and none is public...

**Comment by zkamvar** [comment]
> @zkamvar I took the opportunity to refresh a bit the DESCRIPTION file, so please double check.
> I switched the declaration of authorship to the more modern Authors@R syntax.
> That implied that I had to fill in the tags which were not present.
> I listed all as ctb but you ("cre" + "aut") and @thibautjombart ("aut").
> I added your ORCID number but did not bother with the others.
> I did try for @thibautjombart but could not make sure of which ORCID number was good as several profile exist and none is public...

Thank you! This was something I had been putting off for a while. The only thing I would request from this is to put @thibautjombart first since he was the first author of the package (I've taken over maintenance recently to expedite bug fixes and features). 

Additionally, I've found his ORCiD from https://f1000research.com/articles/8-139/v1: 0000-0003-2226-8692

**Comment by courtiol** [comment]
This should be OK now!

**Comment by zkamvar** [comment]
Looks good to me! Thank you for the contribution :)

**Pull request merged**
