### PR TITLE
Speedup missing import

### PR DESCRIPTION
**Pull request by zkamvar**
See issue #114 for details

### CODE REVIEW

**Comment by thibautjombart** [comment]
Great! In terms of overall speed, are we back to where we were at version 2.0.0? Or better  - I get the 14s but unsure what 27s was referring to?

**Comment by zkamvar** [comment]
27s was referring to how long @thierrygosselin's 1k locus data set took to run on my machine before the changes. The timings after these changes, I listed here: https://github.com/thibautjombart/adegenet/issues/114#issuecomment-162711655

I just took a look with 2.0.0, and 2.0.1 is definitely faster at ~2s vs ~15s for 1k loci.

**Comment by thibautjombart** [comment]
Awesome! Thanks the the update =D


Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by zkamvar** [comment]
Do you think this would be a good point to update CRAN with version 2.0.1?

**Comment by thibautjombart** [comment]
Absolutely! Will try to get this done this week.

**Pull request merged**
